export function init() {
	let LinkMap = new Map();
	LinkMap.set("nadekomedusa", "./assets/DazaiBgs/nadekomedusa.png");
	LinkMap.set("renainadeko", "./assets/DazaiBgs/renainadeko.png");
	LinkMap.set("red", "./assets/DazaiBgs/red.png");
	LinkMap.set("orange", "./assets/DazaiBgs/orange.png");
	LinkMap.set("yellow", "./assets/DazaiBgs/yellow.png");
	LinkMap.set("green", "./assets/DazaiBgs/green.png");
	LinkMap.set("blue", "./assets/DazaiBgs/blue.png");
	LinkMap.set("purple", "./assets/DazaiBgs/purple.png");
	LinkMap.set("spacegray", "./assets/DazaiBgs/spacegray.png");
	LinkMap.set("silver", "./assets/DazaiBgs/silver.png");
	LinkMap.set("rainbowfoil", "./assets/DazaiBgs/rainbowfoil.png");
	LinkMap.set("evenight", "./assets/DazaiBgs/evenight.png");
	LinkMap.set("eve-ning", "./assets/DazaiBgs/eve-ning.jpg");
	LinkMap.set("animenight1", "./assets/DazaiBgs/animenight1.png");
	LinkMap.set("demonslayer1", "./assets/DazaiBgs/demonslayer1.png");
	LinkMap.set("persona3anime", "./assets/DazaiBgs/persona3anime.png");
	LinkMap.set("shirongnl", "./assets/DazaiBgs/shirongnl.png");
	LinkMap.set("berry_pink", "./assets/DazaiBgs/berry_pink.png");
	LinkMap.set("ocean_blue", "./assets/DazaiBgs/ocean_blue.png");
	LinkMap.set("honey_yellow", "./assets/DazaiBgs/honey_yellow.png");
	LinkMap.set("test", "./assets/DazaiBgs/dazaibg.png");
	LinkMap.set("newnadekomedusa","./assets/DazaiBgs/newnadekomedusa.png");
	LinkMap.set("dazai", "./assets/DazaiBgs/dazai.png");
	LinkMap.set("dazai1000", "./assets/DazaiBgs/dazai1000.png");
	LinkMap.set("dazai1000special", "./assets/DazaiBgs/dazai1000special.png");
	LinkMap.set("detective_agency", "./assets/DazaiBgs/detectiveAgency.png");
	LinkMap.set("ani_galaxy", "./assets/DazaiBgs/ani_galaxy.gif");
	LinkMap.set("ani_shelter", "./assets/DazaiBgs/ani_shelter.gif");
	LinkMap.set("ani_demonslayer", "./assets/DazaiBgs/ani_demonslayer.gif");
	LinkMap.set("ani_dazai", "./assets/DazaiBgs/ani_dazai.gif");
	LinkMap.set("genshinXiao", "./assets/DazaiBgs/xiao.png");
	LinkMap.set("matei", "./assets/DazaiBgs/mateiLove.png");
	return LinkMap;
}
export default init;